name: Update Package Version

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npm version patch

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json package-lock.json
          git commit -m "Bump version"

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          branch: ${{ github.ref }}
