name: Package Deployment

on:
  push:
    branches:
      - main

  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
      - uses: MadaraUchiha/copy-action@0.0.1
        with:
          # Source file
          source: ./css
          # Target file
          target: ./dist/esm/css
      - uses: MadaraUchiha/copy-action@0.0.1
        with:
          # Source file
          source: ./css
          # Target file
          target: ./dist/cjs/css
      - uses: MadaraUchiha/copy-action@0.0.1
        with:
          # Source file
          source:
          # Target file
          target:
